server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  application:
    name: web-project-app
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ctrlmysql
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yichen.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# knife4j配置
knife4j:
  enable: true
  openapi:
    title: 停车场管理系统API文档
    description: 停车场管理系统接口文档
    email: admin@example.com
    version: 1.0
    authorization:
      type: bearer
      name: Authorization
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.yichen.controller 